<a href="https://colab.research.google.com/github/SaydahbarovAzamjon-cloud/AI_Foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [33]:
import pandas as pd

In [34]:
print([pd.__version__])

['2.2.2']

In [35]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Bugatti", "Ferarri", "Nissan", "Porsche", "Benz"],
  'counts': [3, 7, 2, 4, 3, 5, 6, 3]
}


df = pd.DataFrame(mydataset)

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6
7     Benz       3

In [36]:
df.head(7) # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6

In [37]:
df.tail() # oxiridan boshlab 5 rows sanaydi

      cars  counts
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6
7     Benz       3

In [38]:
df.shape

(8, 2)

In [39]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [40]:
df.dtypes

cars      object
counts     int64
dtype: object

In [41]:
df.describe() # numerical columns only

         counts
count  8.000000
mean   4.125000
std    1.726888
min    2.000000
25%    3.000000
50%    3.500000
75%    5.250000
max    7.000000

In [42]:
df.describe(include="all")

       cars    counts
count     8  8.000000
unique    8       NaN
top     BMW       NaN
freq      1       NaN
mean    NaN  4.125000
std     NaN  1.726888
min     NaN  2.000000
25%     NaN  3.000000
50%     NaN  3.500000
75%     NaN  5.250000
max     NaN  7.000000

In [43]:
df.iloc[2:4] # 2 qatordan 4 qatorgacha bo'lgan indexlarni olib keladi. [3:] = 3-qatordan boshlab oxirigacha bo'lgan indexni oladi!

      cars  counts
2     Ford       2
3  Bugatti       4

In [44]:
df.loc[:, "cars"]

0        BMW
1      Volvo
2       Ford
3    Bugatti
4    Ferarri
5     Nissan
6    Porsche
7       Benz
Name: cars, dtype: object

In [45]:
df['counts'] > 4

0    False
1     True
2    False
3    False
4    False
5     True
6     True
7    False
Name: counts, dtype: bool

In [46]:
df[df['counts'] > 4] # bu holatda boolean qaytarmasdan faqat 4 dan katta bo'lganlarni oladi!

      cars  counts
1    Volvo       7
5   Nissan       5
6  Porsche       6

In [47]:
df.mean(numeric_only=True)
# df['counts'].mean() # mana bu holatda ham ishlatish mumkin!

counts    4.125
dtype: float64

In [48]:
df.sum() # yeg'indini chiqaradi!

cars      BMWVolvoFordBugattiFerarriNissanPorscheBenz
counts                                             33
dtype: object

In [49]:
df.min()

cars      BMW
counts      2
dtype: object

In [50]:
df.max()

cars      Volvo
counts        7
dtype: object

In [51]:
df.median(numeric_only=True)

counts    3.5
dtype: float64

In [52]:
df.count()

cars      8
counts    8
dtype: int64

In [53]:
df.std(numeric_only=True)

counts    1.726888
dtype: float64

In [54]:
data_with_missing ={
    "cars": ["BMW", "Volvo", None, "Bugatti", "Ferarri", None, "Porsche"],
    "counts": [None, 7, 5, 4, 3, None, 9]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     NaN
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5     None     NaN
6  Porsche     9.0

In [55]:
df_missing.isnull()

    cars  counts
0  False    True
1  False   False
2   True   False
3  False   False
4  False   False
5   True    True
6  False   False

In [56]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [57]:
df_missing.dropna()

      cars  counts
1    Volvo     7.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [58]:
df_missing.dropna(how="all")

      cars  counts
0      BMW     NaN
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [59]:
df_missing.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [60]:
df_missing.dropna(subset=["counts"]) # faqat counts columns ni tekshiradi!

      cars  counts
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [61]:
df_missing.fillna(0) # None qatorlarga data joylaydi

      cars  counts
0      BMW     0.0
1    Volvo     7.0
2        0     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5        0     0.0
6  Porsche     9.0

In [72]:
df_missing.fillna({"cars": "unknow", "counts": 0}) # None qatorlarga data joylaydi

      cars  counts
0      BMW     0.0
1    Volvo     7.0
2   unknow     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5   unknow     0.0
6  Porsche     9.0

In [73]:
# The file 'Titanic-Dataset.csv' was not found, leading to a FileNotFoundError.
# Please ensure this file is uploaded to your Colab environment.
# If the file is located in your Google Drive (which has been mounted),
# you might use a path similar to this:
# df = pd.read_csv("/content/drive/MyDrive/Titanic-Dataset.csv")
# Uncomment the line above and replace 'Titanic-Dataset.csv' with the correct path to your file in Google Drive.

# As 'Titanic-Dataset.csv' is not currently in the environment,
# the original line is commented out to prevent further errors.
# df = pd.read_csv("Titanic-Dataset.csv")

# For demonstration, a small DataFrame is created to allow subsequent code to run without error.
# You should replace this with your actual data loading command once the file is available.
df = pd.DataFrame({'example_col1': [1, 2], 'example_col2': [3, 4]})

df.head()

   example_col1  example_col2
0             1             3
1             2             4

In [74]:
# df = pd.read_csv("Titanic-Dataset.csv")

df = pd.read_excel("Titanic-Dataset.xlsx")
df.tail()

# df = pd.read_json("Titanic-Dataset.json")

FileNotFoundError: [Errno 2] No such file or directory: 'Titanic-Dataset.xlsx'

In [66]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [67]:
df.to_excel("test.xlsx")

In [68]:
# Series => 1D
cars = pd.Series(["BMW", "Volvo", "Ford", "Bugatti", "Ferarri", "Nissan", "Porsche"])
print(cars)

0        BMW
1      Volvo
2       Ford
3    Bugatti
4    Ferarri
5     Nissan
6    Porsche
dtype: object

In [69]:
cars_serise = data_with_missing["cars"]
print(cars_serise)

['BMW', 'Volvo', None, 'Bugatti', 'Ferarri', None, 'Porsche']